 #!/bin/bash

echo -e "\e[34m+----------------+\e[0m"
echo -e "\e[34m| Orchard       |\e[0m"
echo -e "\e[34m| spending key  |\e[0m"
echo -e "\e[34m| sk            |\e[0m"
echo -e "\e[34m+-------+-------+\e[0m"
echo -e "        \e[37m|\e[0m"
echo -e "        \e[37mv\e[0m"
echo -e "\e[32m+---------------------------+\e[0m"
echo -e "\e[32m| Spend authorizing key     |\e[0m"
echo -e "\e[32m| ask                      |\e[0m"
echo -e "\e[32m+---------------------------+\e[0m"
echo -e "        \e[37m|\e[0m"
echo -e "        \e[37mv\e[0m"
echo -e "\e[33m+------------------------------+\e[0m"
echo -e "\e[33m| Full viewing key            |\e[0m"
echo -e "\e[33m| (ak, nk, rivk)              |\e[0m"
echo -e "\e[33m+------------------------------+\e[0m"
echo -e "        \e[37m|\e[0m"
echo -e "        \e[37m+\e[0m------------------------\e[37m+\e[0m------------------------\e[37m+\e[0m"
echo -e "        \e[37m|\e[0m                        \e[37m|\e[0m                        \e[37m|\e[0m"
echo -e "        \e[37mv\e[0m                        \e[37mv\e[0m                        \e[37mv\e[0m"
echo -e "\e[35m+----------------+\e[0m     \e[36m+-------------------+\e[0m   \e[31m+---------------------+\e[0m"
echo -e "\e[35m| Incoming       |\e[0m     \e[36m| Outgoing         |\e[0m   \e[31m| Diversified         |\e[0m"
echo -e "\e[35m| viewing key    |\e[0m     \e[36m| viewing key      |\e[0m   \e[31m| payment addresses   |\e[0m"
echo -e "\e[35m| (dk, ivk)      |\e[0m     \e[36m| ovk              |\e[0m   \e[31m| addr_d = (d, pk_d)  |\e[0m"
echo -e "\e[35m+----------------+\e[0m     \e[36m+-------------------+\e[0m   \e[31m+---------------------+\e[0m"